### ISSUE TITLE
T式によるツリー操作

### ISSUE THREAD

**Issue by ksakam** [kouamano/RECURSIVE-SYSTEM#24]
以下のような操作をT式で記述できるようにする。

(操作)
DB内のツリー群に対して検索を行い、検索結果の(サブ)ツリーやノードを指定して新たなツリーを構成する。

<T式例>
      　　　n1(tree(n2), n3)    　　　  [ni: ノードに対する検索条件(ノードidやノード属性など)]
                          
<意味>
  以下のようなツリー
     ・ルート:N1
     ・子        :DB内でノードN2をルートとする(サブ)ツリー、ノードN3

        [Ni: DB内ツリー内で、検索条件niを満たすノード]
     
<課題>  niに対してNiが複数存在する場合の対応

**Comment by kouamano** [comment]
オペレータ{}の議論に含まれるので、こちらはclose。
