### ISSUE TITLE
treeを再帰レファレンスしたときのセグメンテーションフォルト

### ISSUE THREAD

**Issue by kouamano** [kouamano/RECURSIVE-SYSTEM#29]
echo '##1($##1)' | ./tq.o in=/dev/stdin -Pin -FT
--
##1( ...  $##1@##1($##1@##1($##1@##1($##1@##1($##1@##1($##1@##1($##1@##1($##1@##1($##1@##1セグメンテーション違反です

**Comment by kouamano** [comment]
bind部は再帰しない。    
print部で再帰する。    
永遠に出力され続ける、はずだが、、、

**Comment by ksakam** [comment]
以下のソースを実行
=>"Segmentation fault (core dumped)"　　おそらく無限回再帰コールによるスタックオーバフロー

------------------------------------------
void A()
{
　　A();
}
main()
{
　　A();
}
