### ISSUE TITLE
参照のエンハンス

### ISSUE THREAD

**Issue by ksakam** [kouamano/RECURSIVE-SYSTEM#32]
〇参照の意味
　参照は、参照先(ラベルが付与された頭部またはツリー)への置換を意味する。

[エンハンス項目]
(1)構文の拡張
　参照にも、ラベルやオペレータを付与可とする

(例1) $#1にラベル#2を付与、さらに$#2で参照
- #1Head (#2$#1($#2)) => Head($#1@Head($#2@$#1@Head))

(例2)$#1にオペレータ$`$を付与
- #1List($\`$$#1)=>List($#1@$`$List)=>List($#1@"List")

(2)T式評価オペレータの追加
　参照先への置換時、参照先を評価する/しないを示すオペレータを導入する。

(例) 参照に対するオペレータ例($~$)
- (a) #1$`$List($#1)　=>"List"($#1@"List")　参照先を評価する　　サポート済
- (b) #1$`$List($~$$#1) =>"List"($#1@List)　　　　〃　　しない　未サポート
- (c) #1$`$List($\~$#1)=>"List"($~$#1)　　　置換しない　　　　　サポート済

注: 「$~$」の解釈として、(b)では$#1、(c)では#1が適用対象

(3)同一ヘッドへの複数オペレータの付与
　参照元($#n)にも参照先(#n...)にもオペレータが付与されている場合を考慮して、同一ヘッドに複数のオペレータを付与可とする。
　=> 複数オペレータのセマンティクス明確化

**Comment by kouamano** [comment]
検討事項:

    #1Head (#2$#1($#2)) => Head($#1@Head($#2@$#1@Head))

評価後、ラベルは残すやり方もある。    
"#1Head(#2$#1@#1Head($#2@$#1@#1Head))"

**Comment by kouamano** [comment]
@ksakam 7/16の打ち合わせによれば、エンハンスは無し（必要であれば対応はプリプロセス{}で行う）で良い？

**Comment by ksakam** [comment]
これは別issueと思います。
というか、現状のBNFでは参照の前にlabelはかけてもoperatorは記述不可。(`<label><reference><function><name>...`の順)

なので、issue自体不要というか該当せず、かもしれません。

=>ということでcloseします。
