### ISSUE TITLE
複数T式の扱い

### ISSUE THREAD

**Issue by ksakam** [kouamano/RECURSIVE-SYSTEM#33]
現状のtqにおいて、複数T式の扱いが不明確

(例) A(B)C(D)　　　(入力) A、CをルートとするT式が2つ
=> C(B)(D)　　　　(出力) Cをルート、B、Dが子ノード
　　-0:C:(
　　　　-1:B:)(
　　　　 -2:D:)

<案1> 複数T式の入力は構文エラー扱い
<案2> 複数T式(ツリー)をオペランドとするオペレータを決めて、そのオペレータが省略されているとみなして、入力された複数T式に適用する

=>cqでは当面<案1>で実装済

**Comment by kouamano** [comment]
<案3> ")C("を特殊なデリミタとみなす: Bは無名グループの子ノード、DはグループCに属する子ノード。    
A(B)(D)の現在の解釈が、B、Dが別グループに属する子ノードである、ということからの拡張。    
"@"は予約されているグループでバインドデータグループ。

**Comment by kouamano** [comment]
<案1> にて、一旦完了で良いか?

**Comment by ksakam** [comment]
<案1> にて、一旦完了で良いか?
=>よいと思います。

**Comment by kouamano** [comment]
<案1> を採択。
