### ISSUE TITLE
README.examの移設

### ISSUE THREAD

**Issue by kouamano** [kouamano/RECURSIVE-SYSTEM#47]
- README_base
- その他
に移設

**Comment by ksakam** [comment]
README.examを以下の2つに分離した

- README_base.exam
- README_big.exam

これとあわせて、tqcq.awkを改造
実行結果コンペア用の作業ファイルを、特定のディレクトリ("xxxxx")下に確保

**Comment by kouamano** [comment]
@ksakam これも、closeしてよい？
よければ、closeしてください。

**Comment by ksakam** [comment]
closeします。
