### ISSUE TITLE
LinkTable のノードID(イタレータ)

### ISSUE THREAD

**Issue by kouamano** [kouamano/RECURSIVE-SYSTEM#55]
-1 が使われているので、int型である。-1より小さい数は使われないので、これでは領域の半数が使われない。    
unsigned int を使えるようにIDの振り方を考える。これにより42億objectの格納が可能になる。        
イタレータの導入とポインタ変数格納の廃止の目的は、効率的なノード格納にあるため、上記は必須。

**Comment by kouamano** [comment]
@ksakam closeでよいですね？

**Comment by ksakam** [comment]
> closeでよいですね？

はい、よいと思います。

**Comment by ksakam** [comment]
> > closeでよいですね？

> 
> はい、よいと思います。

来週tdm-libraryの停電復旧後、printを確認してからcloseします。

**Comment by ksakam** [comment]
"-FT -Pin" オプション指定してprintさせても正常終了したのでcloseとします。

time ./c_tq.o in=lllarge-single-test.t.25oku -FT -Pin

=====
[補足](性能)
=====
性能はprintなしで実施。
tdm-libraryマシンで25億ノード※のデータの解析処理(画面1)。
※参考: 2^31-1 = 約21億
従来のint版では、21億ノード付近でsemetation fault(画面2)。
=================
<画面1>(unsigned int版)
=================
$ time ./c_tq.o in=lllarge-single-test.t.25oku
2493077042 Nodes were operated.

real    18m20.142s
user    9m43.088s
sys     8m36.684s

メモリ量は約270GB
=================
<画面2>(従来のint版)
=================
$ time ./c_tq.o in=lllarge-single-test.t.25oku
0
1000000  ←ノード数を表示
   :
2146000000
2147000000
Segmentation fault  <-intの上限値付近で異常終了

real    9m54.444s
user    7m4.273s
sys     2m49.850s
