### ISSUE TITLE
【cqバグ】内積処理時の不正な「,」出力

### ISSUE THREAD

**Issue by ksakam** [kouamano/RECURSIVE-SYSTEM#66]
<現象>
内積処理時、余分な「,」が出力される。

(例)
```
in:
    X(#1A[2],#2B[2],#3C[2])
out:
    $PI$($#1,$#2,$#3@(3333,4444))

data:
Length,Weight
mm,kg
1,2
322,4
5,68
7,81
90,7
100,100
99,99
80,80
77,77
```
(出力結果)
```
./cq.o in=test_ref_prod_inout2.ddf out=test_ref_prod_inout2.ddl data=test.csv -FT -Pin -Pprod -C
X(A[2]@(Length,Weight),B[2]@(mm,kg),C[2]@(1,2))
((Length,mm,,1(3333,4444)),(Weight,kg,,2(3333,4444)))
```
"mm"や"kg"の後の「,,」は不正。本来は「,」(1個のみ)。

<原因>
#65と同様。バインド値の個数として、CSVから読み取った個数を取得すべきところ、@()指定の子ノードの個数を取得していた。
このため、実際にはバインドされた値がない(個数=0)のにある(個数>0)とみなして区切の「,」を出力していた。

<対策>
バインド値の個数を返却する関数として、CSVから読み取ったバインド値の個数を直接返す関数(value_count2(node))と、@()指定の子ノード数を考慮してバインド値の個数を返す関数(value_count(node))を別にした。
＝＞起動する側で使い分ける。

**Comment by kouamano** [comment]
こちらも、tqはどうなっていますかね。

**Comment by ksakam** [comment]
tqでは正しく出力されます。
```
$ ./cq.o in=test_ref_prod_inout2.ddf out=test_ref_prod_inout2.ddl data=test.csv -FT -Pin -Pprod -C
X(A[2]@(Length,Weight),B[2]@(mm,kg),C[2]@(1,2))
((Length,mm,1(3333,4444)),(Weight,kg,2(3333,4444)))
10 Nodes were operated.
```

**Comment by ksakam** [comment]
> tqでは正しく出力されます。

補足します。

今回の不具合の根本原因は、以下にあります。
cqにおいて、@()指定された子ノード数とcsv読込値をバインドした個数とを明確に区別していなかった。

tqにおいては、@()指定ノードにcsv読込値をバインドすることはない(issue#67)ので、今回の不具合は生じないことになります。
