### ISSUE TITLE
テストコードが際限なく増えているので整理

### ISSUE THREAD

**Issue by kouamano** [kouamano/RECURSIVE-SYSTEM#70]
過去のデバグ用テストコードを整理。不要ならば削除。    
対象branchは"cq"と"jsik"。

**Comment by kouamano** [comment]
テストコード削減。
次は、テスト。 => 坂本さんに依頼した。

**Comment by kouamano** [comment]
@ksakam こちらのテストは、たしか、終わりましたよね？

**Comment by ksakam** [comment]
> @ksakam こちらのテストは、たしか、終わりましたよね？

すみません、まだでした。明日いっぱい時間ください。

**Comment by ksakam** [comment]
(不足テストデータ)
　README_base.examに対してtqcq.awkを実行する際に発生するファイル非存在エラー

1. cqブランチ
- test_qesc.csv　　// README_base.examの35行目 -> tq-escape.testの10行目
- test_ref.1.t　　　// 　　　　　〃　　　　160行目

2. jsikブランチ
- test_ref.1.ddf、test_ref.1.ddl　　　// README_base.examの183行目 他
- test_ref.2.ddf、test_ref.2.ddl　　　// 　　　　　〃　　　　187行目 他
- test_ref.2-1.ddl、test_ref.R.2.ddl　 // 　　　　　〃　　　　189、191行目 他

**Comment by kouamano** [comment]
@ksakam もう一度、テストお願いします。対象は cq、cq_debug。
jsikはいったん削除しました。

**Comment by ksakam** [comment]
> @ksakam もう一度、テストお願いします。対象は cq、cq_debug

了解ですが、少々お時間いただきたく。
ちなみに、 cq_debugはcqと何が違うのでしょうか。ソース自体違うのでしょうか。

**Comment by ksakam** [comment]
> @ksakam もう一度、テストお願いします。対象は cq、cq_debug。

(不足テストデータ)
　README_base.examに対してtqcq.awkを実行する際に発生するファイル非存在エラー

1. cqブランチ
- test_ref.1.t　　　// README_base.examの160行目

2. cq_debugブランチ
- test_qesc.csv　　// README_base.examの35行目 -> tq-escape.testの10行目
- test_ref.1.t　　　// 　　　　　〃　　　　160行目

**Comment by kouamano** [comment]
いずれも、不使用にしたはずなので、もう一度てすとおねがいします。
それらしいエラーはない模様。

**Comment by ksakam** [comment]
> いずれも、不使用にしたはずなので、もう一度てすとおねがいします。

すみません、意味を取り違えていて回答遅れました。
再度確認の結果、一部未解決があります。

1. cqブランチ

- test_ref.1.t　　　// README_base.examの160行目
=> 解決

2. cq_debugブランチ

- test_qesc.csv　　// README_base.examの35行目 -> tq-escape.testの10行目
=> まだ発生

- test_ref.1.t　　　// 　　　　　〃　　　　160行目
=> 解決

**Comment by ksakam** [comment]
再度修正いただいた結果、解決しました。closeします。
