### ISSUE TITLE
オペレータ処理の再考

### ISSUE THREAD

**Issue by kouamano** [kouamano/RECURSIVE-SYSTEM#72]
オペレータ"$...$"が動作した時の処理を再定義：
1. オペレータを残したまま機能させる
2. オペレータ部を削除して機能させる（現在のポインタシフトでは対応できないはず）

切り替えはコマンドオプションか？

**Comment by kouamano** [comment]
@ksakam tq型とlisp型に整理したので、close?

**Comment by ksakam** [comment]
> @ksakam tq型とlisp型に整理したので、close?

ですね。ちなみに、以下が正解ですよね?

> 2. オペレータ部を削除して機能させる（現在のポインタシフトでは対応できないはず）
