### ISSUE TITLE
tqcq.awkがヘン

### ISSUE THREAD

**Issue by kouamano** [kouamano/RECURSIVE-SYSTEM#75]
以下を実行した時、
```
./tqcq.awk README.exam
```
README.examに存在しないテキストが出力される

```
### レファレンス
#### 不整合(解消) <= これ
```

**Comment by ksakam** [comment]
```
> ### レファレンス
> #### 不整合(解消) <= これ
```

これは、README.examの11行目、以下のコマンドによる出力です。
`./tqcq.awk README_base.exam`
(README_base.examの87-88行目のコメントが該当)

**Comment by kouamano** [comment]
@ksakam この原因はtq自身にあって、たしか、解消されましたよね？
closeでよいでしょうか。

**Comment by ksakam** [comment]
> @ksakam この原因はtq自身にあって、たしか、解消されましたよね？
> closeでよいでしょうか。

この現象は何かが原因の不具合というより、そもそも期待通りのふるまいです。
closeでよいと思います。
