### ISSUE TITLE
関数名変更

### ISSUE THREAD

**Issue by kouamano** [kouamano/RECURSIVE-SYSTEM#78]
変更して良いか？    
Interpret_Head => Interpret_Operator

**Comment by kouamano** [comment]
@ksakam 変更して良いですかね？

**Comment by ksakam** [comment]
> 変更して良いか？
> Interpret_Head => Interpret_Operator

よろしいと思います。

**Comment by kouamano** [comment]
では、tq/cq変更します。

**Comment by kouamano** [comment]
@ksakam 変更しました。一応、テストお願いします。

**Comment by kouamano** [comment]
@ksakam あ、cq-branchでやってしまいました。
まあ、よいでしょう。cqでテストおねがいします。

**Comment by ksakam** [comment]
了解しました。#70とあわせて「明日いっぱい」ということで。

**Comment by ksakam** [comment]
cqブランチにおいて以下を確認完

・変更前後tq、cqのそれぞれについてREADME_base.exam相当のテストデータを実行し、変更前後の実行結果の一致
・変更後のtq、cqについてREADME_base.examを実行し、tq/cqの実行結果のうち一致すべきものの一致

closeでよいと思います。
