### ISSUE TITLE
オペレータ表現の変更

### ISSUE THREAD

**Issue by kouamano** [kouamano/RECURSIVE-SYSTEM#80]
$xxx$ => {$xxx$ ... }に変更

**Comment by kouamano** [comment]
@ksakam これも、いま、書き換えてしまいますか？

**Comment by ksakam** [comment]
> @ksakam これも、いま、書き換えてしまいますか？

検証してからのほうがよろしいかと。

**Comment by kouamano** [comment]
では、コード検証おねがいします。で、次回発表できれば。

なお、ざっとみたところ、$xxx$というパターンを直接検索しておらず、直前の数字までIndicatorPtrを動かしているようです。

**Comment by ksakam** [comment]
了解ですが、コードの検証というより仕様上の検証がメインと思われます。

**Comment by kouamano** [comment]
@ksakam 7/16の議論によれば、tq型とlisp型に整理されたことにより、このissueは不要？

**Comment by ksakam** [comment]
> @ksakam 7/16の議論によれば、tq型とlisp型に整理されたことにより、このissueは不要？

と思います。
