### ISSUE TITLE
関数名変更

### ISSUE THREAD

**Issue by kouamano** [kouamano/RECURSIVE-SYSTEM#82]
* conj_function
* bopen_function
* head_function
* bclose_function

**Comment by kouamano** [comment]
@ksakam 変更して良いでしょうか。

**Comment by ksakam** [comment]
これらはExFunction_Recursive_Ser_MultiPrintの関数引数と思いますが、これら引数名の変更ですよね？
よろしいと思います。

**Comment by kouamano** [comment]
はい、実際には定義されておらず、変数名です。

**Comment by kouamano** [comment]
@ksakam 変更完了です。そういえば、テストコードで足りないものがあったのですよね？

**Comment by kouamano** [comment]
jsikブランチは、一旦削除します。

**Comment by ksakam** [comment]
> @ksakam 変更完了です。そういえば、テストコードで足りないものがあったのですよね？

はい、#70にリストアップしています。

**Comment by kouamano** [comment]
このissueはcloseします。
