### ISSUE TITLE
import_Tree()のEXEC_FLAG、他

### ISSUE THREAD

**Issue by kouamano** [kouamano/RECURSIVE-SYSTEM#87]
@ksakam 現在使っておらず、今後も使わないと思われるので削除するのが良いと思いますが。

**Comment by ksakam** [comment]
了解いたしました。確かにそのほうがよさそうです。

**Comment by kouamano** [comment]
では、私が修正します。
このコードは、cqにもありますか？

**Comment by ksakam** [comment]
cqにもあります。急ぎでなければわたくしやりますが。(#70の確認とあわせて今週いっぱい)

**Comment by kouamano** [comment]
ほかにも気になるコードがあり、"extra_stat"ですが、命名失敗です。
意味的には、operator_flagかな。
EXEC_FLAGとあわせるなら、大文字。

**Comment by ksakam** [comment]
違ってたらすみません。このフラグは、以前のレビューで話題になった「親関数から子関数への処理指示」に相当するフラグですよね。
このような親関数が増えるごとにフラグのbit数を増やすことになりそうで、どうかという感じです。
<案1> 親から子孫に、フラグはなく処理指示に相当する関数ポインタを渡す(このような親関数がネストしていた場合はこのような親関数ごとに対応する関数ポインタを複数)。
<案2> 内積処理同様、親がツリー内の全子孫ノードに対する処理フローを制御する。

**Comment by kouamano** [comment]
そうですね、「関数は最終的にテーブル管理する」ことを考えれば、「関数ポインタリスト」が良さそうですね。
しかも、渡された順に実行すればよさそうです。そうすると、どうなりますか？
渡すときでなく、その前の処理はどうするのがよさそうか？という意味ですが。

**Comment by ksakam** [comment]
> そうですね、「関数は最終的にテーブル管理する」ことを考えれば、「関数ポインタリスト」が良さそうですね。

はい、それがよさそうです。
ただ、場合によっては<案2>とせざるを得ない場合もでてきそうです。
また、現状では、親関数が子関数に対して指示する関数ポインタは、「,」とか「(」「)」など、「要素間区切りの出力処理」と思いますが、将来的には他の処理についても親が子に指示するケースがでてきそうです。
そうすると、子関数にとって、親から指示された関数ポインタをどのタイミングで起動するかの判断が困難な場合がありそうです。
つまり、関数ポインタとともに、いつ実行するかの指示も必要かもしれません。

> しかも、渡された順に実行すればよさそうです。そうすると、どうなりますか？

「親関数がネストしていた場合は内側が優先」だとすると、最後に渡された関数ポインタのみ実行、といったパタンもないでしょうか。(あるいはその逆)

> 渡すときでなく、その前の処理はどうするのがよさそうか？という意味ですが。

すみません、これはどういう意味でしょうか。

いずれにしろ、本件一般的な扱いはかなり難易度高そうに思えます。

**Comment by kouamano** [comment]
しかも、渡された順に実行すればよさそうです。そうすると、どうなりますか？

単に、関数を実行する順番は、関数ポインタのリストの順、ということです。
ネストの場合は、親関数が順番を変更する場合もある、ということになり、親関数次第と思いますが。
これに伴い、EXEC_FLAGも同様に整理したい（統一可能？）ところですが、これ以上増えないようであれば、このままもありかもしれません。

**Comment by ksakam** [comment]
本日の打合せで、本チケットについては「import_Tree()のEXEC_FLAGの削除だけ実施」でしたでしょうか。(cqブランチにおいて、tq/cq両方)

**Comment by ksakam** [comment]
「import_Tree()のEXEC_FLAGの削除だけ実施」しました(cqブランチのtq/cq両方)。
=> 動作確認済 (tq/cqの両方について、README_base.examの実行結果を修正前後とで比較して一致を確認)

**Comment by kouamano** [comment]
git pushおねがいします。
pushずみでしたか。
よければ、closeして下さい。
