### ISSUE TITLE
機能追加(ダブルアンパック:$UU$)

### ISSUE THREAD

**Issue by ksakam** [kouamano/RECURSIVE-SYSTEM#9]
データ形式定義記述ルールにダブルティルダ(~~)を追加。

- $~~<文字数字>: *リテラルな木(シンボル)、外部システムへ木内の<文字数字>がそのままシンボルとして引き渡される。コンパイル回避にも利用可能。

<例> $~~$X$List($X$A,$X$B) => $X$List($X$A,$X$B)

tqでは実装せず、cqにて実装する。

**Comment by ksakam** [comment]
~~は、tqにて天野さん実装済。

同様の機能追加として、"ダブルアンパック"($UU$...)をcqにて実装する。

**Comment by kouamano** [comment]
$U$、$UU$ともに仕様を再考。

**Comment by ksakam** [comment]
$U$、$UU$について、cqの仕様を現状のtqに合わせた

**Comment by ksakam** [comment]
現仕様で一旦クローズ
